/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Flowery;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
public static int test(){
		test();
		return 0;
	}

}
